import { CSR_UPLOAD_FILE_SELECT } from "./uploadSourceSelect";

export const CSR_DASHBOARD_LEAD_SELECT = {
  id:                 true,
  name:               true,
  company:            true,
  phone:              true,
  email:              true,
  website:            true,
  status:             true,
  nextSchedule:       true,
  nextTime:           true,
  timezone:           true,
  followUpNotes:      true,
  interestedService:  true,
  comments:           true,
  state:              true,
  hiddenOnMain:       true,
  important:          true,
  interested:         true,
  inBin:              true,
  notPickedCount:     true,
  notInterestedCount: true,
  updatedAt:          true,
  createdAt:          true,
  trade:              true,
  subTrades:          true,
  tradeNotes:         true,
  uploadFile:         { select: CSR_UPLOAD_FILE_SELECT },
  _count:             { select: { notes: true } },
} as const;

/** Won clients list — lean payload; full notes on /csr/lead/:id */
export const CSR_CLIENT_LIST_SELECT = {
  id:                 true,
  name:               true,
  company:            true,
  phone:              true,
  email:              true,
  status:             true,
  nextSchedule:       true,
  nextTime:           true,
  timezone:           true,
  followUpNotes:      true,
  interestedService:  true,
  comments:           true,
  state:              true,
  hiddenOnMain:       true,
  important:          true,
  interested:         true,
  inBin:              true,
  notPickedCount:     true,
  notInterestedCount: true,
  updatedAt:          true,
  createdAt:          true,
  trade:              true,
  subTrades:          true,
  tradeNotes:         true,
  uploadFile:         { select: CSR_UPLOAD_FILE_SELECT },
  isOldClient:        true,
  clientCode:         true,
  projectCode:        true,
  projectScope:       true,
  projectBudget:      true,
  paidAmount:         true,
  projectPayments:    true,
    notes: {
    orderBy: { createdAt: "desc" as const },
    take: 20,
    select: { id: true, text: true, createdAt: true, parentId: true },
  },
} as const;

export const CSR_LIST_NOTES_SELECT = {
  orderBy: { createdAt: "desc" as const },
  take: 5,
  select: { id: true, text: true, createdAt: true, parentId: true },
} as const;
